version: '3'

services:
  web:
    image: nginx:latest
    ports:
      - '8088:80'
    volumes:
      - ./web/srcweb:/var/www/html
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - phpfpm
      - mysql

  phpfpm:
    build:
      context: ./api/
      dockerfile: Dockerfile
    #image: php:8-fpm
    volumes:
      - ./web/src:/var/www/html
    #command: docker-php-ext-install mysqli && docker-php-ext-enable mysqli

  adminer:
    image: adminer
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    restart: always
    ports:
      - 8080:8080
    links:
      - mysql

  mysql:
    image: mysql:latest
    container_name: docker-mysql
    environment:
      MYSQL_DATABASE: prueba
      MYSQL_USER: my_sql_user
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - ./data-db:/var/lib/mysql
    restart: always

  