name: Pipeline Principal

on: 
  pull_request:
    branches:
      - master
      - produccion
    types:
      - closed 

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:    
      - name: Descarga repo
        uses: actions/checkout@v3
     
      - name: Linting PHP
        uses: StephaneBour/actions-php-lint@8.2
        with:
          dir: './src/web/srcweb'

      - name: Configuración credenciales AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1
   
      - name: Validar Terraform
        run: |
          docker-compose -f deploy/docker-compose.yml run --rm terraform init     
          docker-compose -f deploy/docker-compose.yml run --rm terraform fmt  
          docker-compose -f deploy/docker-compose.yml run --rm terraform validate
  

      - name: Login en AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build, tag, push image ECR - Proxy
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_PROXY: app-api-proxy
          IMAGE_PROXY_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_PROXY:$IMAGE_PROXY_TAG . -f src/web/Dockerfile
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_PROXY:$IMAGE_PROXY_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY_PROXY:$IMAGE_PROXY_TAG $ECR_REPOSITORY_PROXY:latest
          docker push $ECR_REPOSITORY_PROXY:latest
          echo "Cambios realizados Proxy"

      - name: Build, tag, push image ECR API
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY_API: app-api-api
          IMAGE_API_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_API_TAG . -f src/api/Dockerfile
          docker push $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_API_TAG
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY_API:$IMAGE_API_TAG $ECR_REPOSITORY_API:latest
          docker push $ECR_REPOSITORY_API:latest
          echo "Cambios realizados Api"

      - name: Terraform Plan
        run: |
          docker-compose -f deploy/docker-compose.yml run --rm terraform workspace select "staging"
          docker-compose -f deploy/docker-compose.yml run --rm terraform plan

      - name: Terraform Apply Desarrollo
        if: github.ref_name == 'master'
        run: |         
          docker-compose -f deploy/docker-compose.yml run --rm terraform workspace select "staging"  
          docker-compose -f deploy/docker-compose.yml run --rm terraform apply -auto-approve
  

      - name: Terraform Apply Produccion
        if: github.ref_name == 'produccion'
        run: |         
          docker-compose -f deploy/docker-compose.yml run --rm terraform workspace select "produccion"  
          docker-compose -f deploy/docker-compose.yml run --rm terraform apply -auto-approve